[package]
name = "secret-user-imports"
version = "0.1.0"
edition = "2021"

[dependencies]
secret_user = { path = "../" }
marine-rs-sdk = { version="0.14.0" }
marine-error = { path = "../../../../crates/marine-error" }
