total_memory_limit = "2GB"

[[module]]
name = "use_secret_module"
load_from = "/Users/miruzavin/private/fluence/crypto/target/wasm32-wasi/release/use_secret_module.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/modules/use_secret_module/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/modules/use_secret_module/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"

[[module]]
name = "secret_user_with_use"
load_from = "/Users/miruzavin/private/fluence/crypto/src/services/modules/secret-user-with-use/secret_user_with_use.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/modules/secret_user_with_use/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user-2/modules/secret_user_with_use/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"
