total_memory_limit = "2GB"

[[module]]
name = "secret_user_default"
load_from = "/Users/miruzavin/private/fluence/crypto/src/services/modules/secret-user-default/secret_user_default.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user/modules/secret_user_default/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-user/modules/secret_user_default/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"
