total_memory_limit = "2GB"

[[module]]
name = "secret_mover"
load_from = "/Users/miruzavin/private/fluence/crypto/target/wasm32-wasi/release/secret_mover.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/secret_mover/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/secret_mover/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"

[[module]]
name = "localfile_adapter"
load_from = "/Users/miruzavin/private/fluence/crypto/target/wasm32-wasi/release/localfile_adapter.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/localfile_adapter/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/localfile_adapter/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"

[[module]]
name = "sqlite3"
load_from = "/Users/miruzavin/private/fluence/crypto/.fluence/modules/sqlite3.tar.gz_d35d7a28b1a8a55e87df96578d70ad46/sqlite3.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/sqlite3/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/sqlite3/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"

[[module]]
name = "secret_saver_adapter"
load_from = "/Users/miruzavin/private/fluence/crypto/target/wasm32-wasi/release/secret_saver_adapter.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/secret_saver_adapter/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/secret_saver_adapter/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"

[[module]]
name = "crypto_module"
load_from = "/Users/miruzavin/private/fluence/crypto/target/wasm32-wasi/release/crypto_module.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/crypto_module/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/crypto_module/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"

[[module]]
name = "secret_facade"
load_from = "/Users/miruzavin/private/fluence/crypto/target/wasm32-wasi/release/secret_facade.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/tmp"
"/storage" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/service/storage"
"/tmp/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/secret_facade/tmp/module"
"/storage/module" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/services/secret-holder/modules/secret_facade/storage/module"
"/tmp/vault" = "/Users/miruzavin/private/fluence/crypto/.fluence/tmp/volumes/particles"
