modules_dir = "../../artifacts/"
total_memory_limit = "Infinity"

[[module]]
name = "localfile_adapter"

[module.wasi.mapped_dirs]
"/tmp" = "./tmp/secret-holder/tmp"
"/storage" = "./tmp/secret-holder/storage"
"/tmp/module" = "./tmp/secret-holder/tmp/module/localfile_adapter"
"/storage/module" = "./tmp/secret-holder/storage/module/localfile_adapter"
"/tmp/vault" = "./tmp/vault"

[[module]]
name = "sqlite3"

[module.wasi.mapped_dirs]
"/tmp" = "./tmp/secret-holder/tmp"
"/storage" = "./tmp/secret-holder/storage"
"/tmp/module" = "./tmp/secret-holder/tmp/module/sqlite3"
"/storage/module" = "./tmp/secret-holder/storage/module/sqlite3"
"/tmp/vault" = "./tmp/vault"

[[module]]
name = "secret_saver_adapter"
logger_enabled = true

[[module]]
name = "secret_mover"
logger_enabled = true

[module.wasi.mapped_dirs]
"/tmp" = "./tmp/secret-holder/tmp"
"/storage" = "./tmp/secret-holder/storage"
"/tmp/module" = "./tmp/secret-holder/tmp/module/secret_mover"
"/storage/module" = "./tmp/secret-holder/storage/module/secret_mover"
"/tmp/vault" = "./tmp/vault"

[[module]]
name = "crypto_module"
logger_enabled = true

[[module]]
name = "secret_facade"
logger_enabled = true
