modules_dir = "../../artifacts/"
total_memory_limit = "Infinity"

[[module]]
name = "secret_user"

[module.wasi.mapped_dirs]
"/tmp" = "./tmp/secret-user/tmp"
"/storage" = "./tmp/secret-user/storage"
"/tmp/module" = "./tmp/secret-user/tmp/module"
"/storage/module" = "./tmp/secret-user/storage/module"
"/tmp/vault" = "./tmp/vault"